name: Generate Second Snake

on:
  schedule:
    - cron: "0 1 * * *" # Runs 1 hour after the first one to avoid conflicts
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Grigarin-5
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push Snake Output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output2
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
